version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_PASSWORD}"
        POSTGRES_HOST: "${POSTGRES_HOST}"
        DATABASE_PORT: "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - /var/data_comm/postgresql:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: always
    env_file:
      - .env

  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
        - postgres
        - redis
    env_file:
      - .env
    volumes:
      - .:/app
#  test:
#    build: .
#    command: pytest

volumes:
    postgres-data: