"""Second commit

Revision ID: 4246325eb7ce
Revises: 5a795ad8be40
Create Date: 2024-04-19 12:18:58.479584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4246325eb7ce'
down_revision: Union[str, None] = '5a795ad8be40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('User', sa.Column('lastname', sa.String(), nullable=True))
    op.drop_column('User', 'user_lastname')
    op.drop_column('User', 'user_firstname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('user_firstname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('user_lastname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('User', 'lastname')
    op.drop_column('User', 'firstname')
    # ### end Alembic commands ###
